name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Generate key
        run: php artisan key:generate --force

      - name: Migrate database
        run: php artisan migrate --force

      - name: Cache clear
        run: php artisan cache:clear

      - name: Clear config cache
        run: php artisan config:cache

      - name: Clear route cache
        run: php artisan route:cache

      - name: Clear view cache
        run: php artisan view:clear

      - name: Archive application
        run: tar -czf app.tar.gz .

      - name: Move deployment archive
        run: mv app.tar.gz /var/www/app.prodriversafrica.com

      - name: Extract deployment archive
        run: |
          cd /var/www/app.prodriversafrica.com
          tar -xzf app.tar.gz

      - name: Change ownership of /var/www
        run: |
          # set webserver as owner as files
          sudo -S <<< ${{ secrets.USER_PASS }} chown -R www-data:www-data /var/www/app.prodriversafrica.com
          # add user to webserver group
          sudo -S <<< ${{ secrets.USER_PASS }} usermod -a -G www-data ubuntu

      - name: Set file permissions
        run: |
          chmod -R 755 /var/www/app.prodriversafrica.com
          find /path/to/your/laravel/root/directory -type f -exec chmod 644 {} \;
          find /path/to/your/laravel/root/directory -type d -exec chmod 755 {} \;
          chgrp -R www-data storage bootstrap/cache
          chmod -R ug+rwx storage bootstrap/cache
